Issue 116: Add functions for Rt and growth rates as outputs
CDCgov/Rt-without-renewal pull request #184
Opened 2024-04-21 19:52 UTC by seabbs

This started as a PR for #165 (hence the branch name) but is just addressing (and closing #116) as #165 is turning out to be a little more complex than expected. 

Here we add two new functions

- `expected_Rt` Dispatching on a `EpiData` object or taking arguments directly.
- `expected_rt` dispatching on a vector and taking the log differences.

2024-05-30 15:37 UTC, seabbs commented
Closing as we. are now planing on doing this within the inf submodel

2024-05-30 15:45 UTC, seabbs commented
Okay looking at this again I vote to review and merge as a partial PR towards #116 leaving the expected growth rate to work out

2024-06-03 12:43 UTC, SamuelBrand1 commented on EpiAware/src/EpiInfModels/EpiData.jl
> +expected_Rt(data, infections)
close the example block

2024-06-03 12:45 UTC, SamuelBrand1 commented on EpiAware/src/EpiInfModels/EpiData.jl
> +```julia
```suggestion
```julia
using EpiAware
data = EpiData([0.2, 0.3, 0.5], exp)
infections = [100, 200, 300, 400, 500]
expected_Rt(data, infections)
```
```

2024-06-03 12:47 UTC, SamuelBrand1 commented on EpiAware/src/EpiInfModels/EpiData.jl
> +    denom_Rt = [dot(reverse(data.gen_int),
Might be worth having an `@assert` on length of infections vs `n`

2024-06-03 12:51 UTC, SamuelBrand1 requested changes
LGTM. One docstring small fix.

Worth noting that this will give the _effective_ $R_t$ as opposed to unadjusted $R_t$; this will diverge as we add population effects e.g. #245 . This is a good thing but maybe also mention in docstring.

2024-06-03 15:55 UTC, seabbs commented
> Worth noting that this will give the effective  as opposed to unadjusted 

I think we should put this in the paper as a discussion point

2024-06-04 09:11 UTC, SamuelBrand1 commented
> > Worth noting that this will give the effective  as opposed to unadjusted
> 
> I think we should put this in the paper as a discussion point
> 
> > One docstring small fix.
> 
> Do we have anything in CI etc that tests docstring examples at least run / docstrings are valid? It seems like this is quite important so it would be odd if the julia community didn't have tools for this

https://documenter.juliadocs.org/stable/man/doctests/#Doctesting-as-Part-of-Testing

IIRC we have talked about this but not done it yet.

2024-06-04 09:13 UTC, SamuelBrand1 approved these changes
LGTM

2024-06-04 09:13 UTC, merged