Include day of week effect in pipeline analysis
CDCgov/Rt-without-renewal pull request #264
Opened 2024-06-07 12:13 UTC by SamuelBrand1

Small PR which implements the day of week observation effect introduced by #253 and #258  to the pipeline generative model. Also removes older "truth data" sims.

Closes #257 .

2024-06-07 13:41 UTC, seabbs requested changes
This looks good but has there been a git history issue here? Looks like a bunch of changes I thought we had merged already. 

Also looks like some files have been committed accidentally. Suggest using a .gitignore in truth data and adding these file types + getting rid of the placeholder file. Or do we want to commit this data as fixes the sims for onwards analysis?

2024-06-07 13:48 UTC, SamuelBrand1 commented on EpiAware/src/EpiLatentModels/HierarchicalNormal.jl
> +    ϵ_t ~ MvNormal(n, one(eltype(std)))
Commit history

2024-06-07 13:48 UTC, SamuelBrand1 commented
> This looks good but has there been a git history issue here? Looks like a bunch of changes I thought we had merged already.

I started this branch before these changes were merged to main and squashed them into this branch.

2024-06-07 13:59 UTC, seabbs commented
That doesn't sound like the right git flow to me? I've rebase so maybe will fix

2024-06-07 14:12 UTC, seabbs reviewed
Rebased fixed the issue with old stuff here but commited files are still here. Are they meant to be?

2024-06-07 14:42 UTC, SamuelBrand1 commented
> Rebased fixed the issue with old stuff here but commited files are still here. Are they meant to be?

I don't see any committed files except some placeholder.md files?

2024-06-10 18:11 UTC, seabbs approved these changes

2024-06-11 08:20 UTC, merged